//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaveBrownPhotography.Fashion {
    
    
    public partial class Home {
        
        /// <summary>
        /// latestBlogs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DaveBrownPhotography.Controls.LatestBlogPosts latestBlogs;
    }
}
